export const Categories = [
  {
    id: 'mens-wear',
    name: "Men's Wear",
    slug: 'mens-wear',
    description: 'T-shirts, jeans, shirts, suits, and more for men.',
    image: 'https://images.pexels.com/photos/32435002/pexels-photo-32435002.jpeg',
  },
  {
    id: 'womens-wear',
    name: "Women's Wear",
    slug: 'womens-wear',
    description: 'Dresses, tops, skirts, ethnic wear, and more.',
    image: 'https://images.pexels.com/photos/13593505/pexels-photo-13593505.jpeg',
  },
  {
    id: 'kids-wear',
    name: "Kids' Wear",
    slug: 'kids-wear',
    description: 'Clothing for boys, girls, and toddlers.',
    image: 'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg',
  },
  {
    id: 'footwear',
    name: 'Footwear',
    slug: 'footwear',
    description: 'Sneakers, boots, sandals, and formal shoes.',
    image: 'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg',
  },
  {
    id: 'activewear',
    name: 'Activewear',
    slug: 'activewear',
    description: 'Gym clothes, yoga pants, sportswear, and more.',
    image: 'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg',
  },
  {
    id: 'innerwear',
    name: 'Innerwear & Loungewear',
    slug: 'innerwear',
    description: 'Comfortable underwear, sleepwear, and robes.',
    image: 'https://images.pexels.com/photos/13593505/pexels-photo-13593505.jpeg',
  },
  {
    id: 'winterwear',
    name: 'Winterwear',
    slug: 'winterwear',
    description: 'Jackets, coats, sweaters, and thermals.',
    image: 'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg',
  },
  {
    id: 'accessories',
    name: 'Accessories',
    slug: 'accessories',
    description: 'Bags, belts, watches, sunglasses, and more.',
    image: 'https://images.pexels.com/photos/13593505/pexels-photo-13593505.jpeg',
  },
  {
    id: 'ethnic',
    name: 'Ethnic & Traditional',
    slug: 'ethnic',
    description: 'Kurtas, sarees, lehengas, and ethnic sets.',
    image: 'https://images.pexels.com/photos/13593505/pexels-photo-13593505.jpeg',
  },
  {
    id: 'denim',
    name: 'Denim',
    slug: 'denim',
    description: 'Jeans, denim jackets, skirts, and shirts.',
    image: 'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg',
  }
];
