export const Categories = [
    {
        id: 'mens-wear',
        name: "Men's Wear",
        slug: 'mens-wear',
        description: 'T-shirts, jeans, shirts, suits, and more for men.',
        image: '/images/categories/mens-wear.png',
    },
    {
        id: 'womens-wear',
        name: "Women's Wear",
        slug: 'womens-wear',
        description: 'Dresses, tops, skirts, ethnic wear, and more.',
        image: '/images/categories/womens-wear.png',
    },
    {
        id: 'kids-wear',
        name: "Kids' Wear",
        slug: 'kids-wear',
        description: 'Clothing for boys, girls, and toddlers.',
        image: '/images/categories/kids-wear.png',
    },
    {
        id: 'footwear',
        name: 'Footwear',
        slug: 'footwear',
        description: 'Sneakers, boots, sandals, and formal shoes.',
        image: '/images/categories/footwear.png',
    },
    {
        id: 'activewear',
        name: 'Activewear',
        slug: 'activewear',
        description: 'Gym clothes, yoga pants, sportswear, and more.',
        image: '/images/categories/activewear.png',
    },
    {
        id: 'innerwear',
        name: 'Innerwear & Loungewear',
        slug: 'innerwear',
        description: 'Comfortable underwear, sleepwear, and robes.',
        image: '/images/categories/innerwear.png',
    },
    {
        id: 'winterwear',
        name: 'Winterwear',
        slug: 'winterwear',
        description: 'Jackets, coats, sweaters, and thermals.',
        image: '/images/categories/winterwear.png',
    },
    {
        id: 'accessories',
        name: 'Accessories',
        slug: 'accessories',
        description: 'Bags, belts, watches, sunglasses, and more.',
        image: '/images/categories/accessories.png',
    },
    {
        id: 'ethnic',
        name: 'Ethnic & Traditional',
        slug: 'ethnic',
        description: 'Kurtas, sarees, lehengas, and ethnic sets.',
        image: '/images/categories/ethnic.png',
    },
    {
        id: 'denim',
        name: 'Denim',
        slug: 'denim',
        description: 'Jeans, denim jackets, skirts, and shirts.',
        image: '/images/categories/denim.png',
    }
];
