import type { Metadata } from "next";
import { Outfit, Instrument_Sans } from "next/font/google";
import "./globals.css";
import { cookies } from 'next/headers';
// import Header from "@/components/Header-footer/Header";
// import Footer from "@/components/Header-footer/Footer";

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-outfit',
});

const instrumentSans = Instrument_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-instrument',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const theme = (await cookies()).get('theme')?.value || 'default';

  const Header = (await import(`@/components/${theme}/Header-footer/Header`)).default;
  const Footer = (await import(`@/components/${theme}/Header-footer/Footer`)).default;

  return (
    <html lang="en" className={`${outfit.variable} ${instrumentSans.variable}`}>
      <body className="font-[instrument_Sans]">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
