// lib/products.ts

export const bestSellers = [
    {
        id: 1,
        slug: "off-duty-fit-set",
        title: "FlexForm Performance T SHIRT",
        brand: "CoreFlex",
        price: 20,
        oldPrice: 25,
        image: "/images/product-image.png",
    },
    {
        id: 2,
        slug: "off-duty-fit-set",
        title: "FlexForm Performance Set",
        brand: "CoreFlex",
        price: 20,
        oldPrice: 25,
        image: "/images/product-image.png",
    },
    {
        id: 3,
        slug: "off-duty-fit-set",
        title: "FlexForm Performance Set",
        brand: "CoreFlex",
        price: 20,
        oldPrice: 25,
        image: "/images/product-image.png",
    },
    {
        id: 4,
        slug: "off-duty-fit-set",
        title: "FlexForm Performance Set",
        brand: "CoreFlex",
        price: 20,
        oldPrice: 25,
        image: "/images/product-image.png",
    },
    {
        id: 5,
        slug: "off-duty-fit-set",
        title: "FlexForm Performance Set",
        brand: "CoreFlex",
        price: 20,
        oldPrice: 25,
        image: "/images/product-image.png",
    },
    {
        id: 6,
        slug: "off-duty-fit-set",
        title: "FlexForm Performance Set",
        brand: "CoreFlex",
        price: 20,
        oldPrice: 25,
        image: "/images/product-image.png",
    },
    {
        id: 7,
        slug: "off-duty-fit-set",
        title: "FlexForm Performance Set",
        brand: "CoreFlex",
        price: 20,
        oldPrice: 25,
        image: "/images/product-image.png",
    },
    {
        id: 8,
        slug: "off-duty-fit-set",
        title: "FlexForm Performance Set",
        brand: "CoreFlex",
        price: 20,
        oldPrice: 25,
        image: "/images/product-image.png",
    },
    {
        id: 9,
        slug: "off-duty-fit-set",
        title: "FlexForm Performance Set",
        brand: "CoreFlex",
        price: 20,
        oldPrice: 25,
        image: "/images/product-image.png",
    },
    {
        id: 10,
        slug: "off-duty-fit-set",
        title: "FlexForm Performance Set",
        brand: "CoreFlex",
        price: 20,
        oldPrice: 25,
        image: "/images/product-image.png",
    },
    {
        id: 11,
        slug: "off-duty-fit-set",
        title: "FlexForm Performance Set",
        brand: "CoreFlex",
        price: 20,
        oldPrice: 25,
        image: "/images/product-image.png",
    },
    {
        id: 12,
        slug: "off-duty-fit-set",
        title: "FlexForm Performance Set",
        brand: "CoreFlex",
        price: 20,
        oldPrice: 25,
        image: "/images/product-image.png",
    },
];
