// import ManuSidebar from "@/components/manu-pages/ManuSidebar";
import type { Metadata } from "next";
import { cookies } from 'next/headers';


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    type ThemeKey = 'theme1' | 'theme2' | 'theme3';
    const theme = ((await cookies()).get('theme')?.value as ThemeKey) || 'default';

    const ManuSidebarMap = {
        theme1: () => import('@/components/theme1/manu-pages/ManuSidebar'),
        theme2: () => import('@/components/theme2/manu-pages/ManuSidebar'),
        theme3: () => import('@/components/theme3/manu-pages/ManuSidebar'),
    };

    const ManuSidebar = (await ManuSidebarMap[theme]())?.default;

    return (
        <>
            <ManuSidebar />
            {children}
        </>
    );
}
